### ISSUE TITLE
make sure csv implementation is platform independent

### ISSUE THREAD

**Issue by kcranston** [AAFC-BICoE/specify-scripts#8]
Need to make sure that the implementation will work on all platforms (i.e. input and output files can be read on Windows and Linux systems).

**Comment by brookeclouston** [comment]
It appears that the only implementation issue for _reading_ csv files between Linux and Windows is the `newline=""`  addition to the open statement, which both [ReplaceAgents](https://github.com/AAFC-BICoE/specify-scripts/blob/RemoveAgents/ReplaceAgents.py) and[ ImagePull](https://github.com/AAFC-BICoE/specify-scripts/blob/ImageSearch/ImagePull.py) have. 

For _writing_  csv files, the[ csvwriter.py](https://github.com/AAFC-BICoE/specify-scripts/commit/a524587583bdf2609026dd533b3e770c9ac22c2e) module has been updated to account for the difference in operating systems. 

Source: this stackoverflow [question](https://stackoverflow.com/questions/7200606/python3-writing-csv-files)
